// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TalStart.Models;

#nullable disable

namespace TalStart.Migrations
{
    [DbContext(typeof(TalStartContext))]
    partial class TalStartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TalStart.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("TalStart.Models.PipelineDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DestinationDatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("Json")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourceDatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinationDatasetId");

                    b.HasIndex("SourceDatasetId");

                    b.HasIndex("Username");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("TalStart.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TalStart.Models.Dataset", b =>
                {
                    b.HasOne("TalStart.Models.User", "User")
                        .WithMany("ListOfDataSets")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalStart.Models.PipelineDbo", b =>
                {
                    b.HasOne("TalStart.Models.Dataset", "DestinationDataset")
                        .WithMany()
                        .HasForeignKey("DestinationDatasetId");

                    b.HasOne("TalStart.Models.Dataset", "SourceDataset")
                        .WithMany()
                        .HasForeignKey("SourceDatasetId");

                    b.HasOne("TalStart.Models.User", "User")
                        .WithMany("ListOfPipelines")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationDataset");

                    b.Navigation("SourceDataset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalStart.Models.User", b =>
                {
                    b.Navigation("ListOfDataSets");

                    b.Navigation("ListOfPipelines");
                });
#pragma warning restore 612, 618
        }
    }
}
